IMG_CONTEXT_TOKEN = "<IMG_CONTEXT>"
IMG_START_TOKEN = "<img>"
IMG_END_TOKEN = "</img>"
QUAD_START_TOKEN = "<quad>"
QUAD_END_TOKEN = "</quad>"
REF_START_TOKEN = "<ref>"
REF_END_TOKEN = "</ref>"
BOX_START_TOKEN = "<box>"
BOX_END_TOKEN = "</box>"
CONV_START_TOKEN = "<|im_start|>"
CONV_END_TOKEN = "<|im_end|>"
ACTION_START_TOKEN = "<|action_start|>"
ACTION_END_TOKEN = "<|action_end|>"
PLUG_TOKEN = "<|plugin|>"
INTERPRETER_TOKEN = "<|interpreter|>"
THINK_START_TOKEN = "<think>"
THINK_END_TOKEN = "</think>"

ALL_SPECIAL_TOKEN_LIST = [
    IMG_CONTEXT_TOKEN,
    IMG_START_TOKEN,
    IMG_END_TOKEN,
    QUAD_START_TOKEN,
    QUAD_END_TOKEN,
    REF_START_TOKEN,
    REF_END_TOKEN,
    BOX_START_TOKEN,
    BOX_END_TOKEN,
    CONV_START_TOKEN,
    CONV_END_TOKEN,
    ACTION_START_TOKEN,
    ACTION_END_TOKEN,
    PLUG_TOKEN,
    INTERPRETER_TOKEN,
]

IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)
CLIP_MEAN = (0.4814546, 0.4578275, 0.40821073)
CLIP_STD = (0.2686295, 0.2613025, 0.2757711)
SIGLIP_MEAN = (0.5, 0.5, 0.5)
SIGLIP_STD = (0.5, 0.5, 0.5)

IGNORE_INDEX = -100
